on:
  workflow_call:
    inputs:
      image_to_push:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      tag_latest:
        required: false
        type: boolean
        default: false
      image_repository:
        required: false
        type: string
        default: ghcr.io/${{ github.repository }}

name: Build Container - Template

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: "${{inputs.image_repository}}/${{ inputs.image_to_push }}"

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      # Replace this login step if you use a container repository other than github packages.
      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build Docker Image
        run: |
          BuildConfiguration=Release docker-compose build ${{ inputs.image_to_push }}

      - name: Create Tag
        run: |
          IMAGE_TAG=$IMAGE_PATH:$(echo ${{ inputs.tag_name }} | sed 's/[^a-zA-Z0-9]/-/g')
          # Make characters lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
          echo "Tagging ${{ inputs.image_to_push }} with $IMAGE_TAG in GitHub Container Registry"
          docker tag ${{ inputs.image_to_push }} $IMAGE_TAG

      - name: Tag Latest
        if: ${{ inputs.tag_latest }}
        run: |
          IMAGE_TAG_LATEST=$IMAGE_PATH:latest
          # Make characters lowercase
          IMAGE_TAG_LATEST=$(echo $IMAGE_TAG_LATEST | tr '[:upper:]' '[:lower:]')
          echo "Tagging ${{ inputs.image_to_push }} with $IMAGE_TAG_LATEST in GitHub Container Registry"
          docker tag ${{ inputs.image_to_push }} $IMAGE_TAG_LATEST

      - name: Publish Image
        run: |
          echo "Pushing ${{ inputs.image_to_push }} to GitHub Container Registry"
          # Make characters lowercase
          IMAGE_PUSH_PATH=$(echo $IMAGE_PATH | tr '[:upper:]' '[:lower:]')
          docker push --all-tags $IMAGE_PUSH_PATH
